AWSTemplateFormatVersion: "2010-09-09"
Description: flyway lambda with migration scripts in S3
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Secret:
    Type: String
  SecretArn:
    Type: String
  ConnectionString:
    Type: String
    NoEcho: true
  GitSecretName:
    Type: String
    Description: Secrets manager secret name to hold git secrets
  GitUser:
    Type: String
    NoEcho: true
  GitPassword:
    Type: String
    NoEcho: true
  GitRepo:
    Type: String
Resources:
  GitSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref GitSecretName
      Description: Flyway lambda git repo secrets
      SecretString: !Sub '{"username": ${GitUser},"password": ${GitPassword}}'

  FlywayLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version : "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Join ['', ['arn:', !Ref 'AWS::Partition', ':iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole']]
      Policies:
        - PolicyName: "LambdaExecutionRolePolicy"
          PolicyDocument :
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:GetSecretValue"
                Resource: !Ref SecretArn

  FlywayLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Flyway lambda security group to access VPC
      VpcId: !Ref VPC

  DBFlywaySgRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt FlywayLambdaSecurityGroup.GroupId
      GroupId: !Ref RDSSecurityGroup

  FlywayLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: FlywayLambda
      Code: flyway-lambda.jar
      Description: Flyway lambda
      Environment:
        Variables:
          DB_SECRET: !Ref Secret
          GIT_SECRET: !Ref GitSecret
          DB_CONNECTION_STRING: !Ref ConnectionString
          GIT_REPOSITORY: !Ref GitRepo
      Handler: com.geekoosh.flyway.FlywayHandler::handleRequest
      MemorySize: 256
      Role: !GetAtt FlywayLambdaExecutionRole.Arn
      Runtime: java8
      Timeout: 120
      VpcConfig:
        SecurityGroupIds:
          - !Ref FlywayLambdaSecurityGroup
        SubnetIds: !Ref Subnets
