AWSTemplateFormatVersion: "2010-09-09"
Description: RDS instance with secrets manager
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  Username:
    Type: String
  DBName:
    Type: String
    Default: postgres
  InstanceType:
    Type: String
    Default: db.t3.small
Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Postgres password'
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${Username}"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
  DB:
    Properties:
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !Ref InstanceType
      AllocatedStorage: 10
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: postgres
      EngineVersion: '11.5'
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}' ]]
      StorageType: gp2
      MultiAZ: false
      VPCSecurityGroups:
        - Ref: DBSecurityGroup
    Type: AWS::RDS::DBInstance

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref DB
      TargetType: AWS::RDS::DBInstance

  DBSecurityGroup:
    Properties:
      GroupDescription: Postgres Security Group
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup

  DBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds: !Ref Subnets
    Type: AWS::RDS::DBSubnetGroup
